name: Run checks

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK with maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        shell: bash
        run: mvn package --file pom.xml

      - name: Run tests
        shell: bash
        run: mvn test
